// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iudockudmdqjrpnbunct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1ZG9ja3VkbWRxanJwbmJ1bmN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjE3MjgsImV4cCI6MjA2NTkzNzcyOH0.6GjPTVqDFT-1cVHzMz5Wang2jv7TdtIY7HvOrRoJzto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);